### ISSUE TITLE
Copy of the sample data

### ISSUE THREAD

**Issue by shamilnabiyev** [fernandodecastilla/Machine-Learning-for-Predictive-Maintenance#1]
Hi Fernando. Thank you very much for the amazing tutorial. Unfortunately the URL in the README seems to be deactivated. I'd like to use the dataset for my master's thesis. Have you got a local copy of the sample data?

**Comment by fernandodecastilla** [comment]
Hi Shamil,

Sorry for the inconvenience. The dataset was accessed by Microsoft URL, but last year the link stopped working.

Some people asked me for the dataset, but I didn’t save any copy due to its big size.

Best regards.

Fernando de Castilla

Enviado desde mi iPhone

El 16 abr 2022, a las 12:47, Shamil Nabiyev ***@***.***> escribió:

﻿

Hi Fernando. Thank you very much for the amazing tutorial. Unfortunately the URL in the README seems to be deactivated. I'd like to use the dataset for my master's thesis. Have you got a local copy of the sample data?

**Comment by shamilnabiyev** [comment]
It's OK :) Thank you very much, Fernando.
